#!/bin/bash
#
# clean the case

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# remove mesh
rm -f geometry.msh
rm -rf constant/polyMesh/*

rm -rf 0 > /dev/null 2>&1

cleanCase
