#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./meshIt

# uncomment the line below if you changed the geometry
#openscad -o constant/triSurface/pipe.stl pipe.scad

#runApplication blockMesh # blockMesh called by ./meshIt
runApplication surfaceFeatureExtract
runApplication surfaceFeatureConvert constant/triSurface/pipe.eMesh features.obj
runApplication snappyHexMesh 
