#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allclean

# uncomment the line below if you changed the geometry
#openscad -o constant/triSurface/pipe.stl crossedPipes.scad

runApplication blockMesh
runApplication surfaceFeatureExtract
runApplication surfaceFeatureConvert constant/triSurface/pipe.eMesh features.obj
runApplication snappyHexMesh #-overwrite
